#!/usr/bin/env python3
"""Generate `tests/fixtures/grid_golden.json` — the square grid's behaviour.

    python3 tests/grid_golden.py --generate

**Run this on `origin/main`, before the #146 refactor, and commit the result.**
That ordering is the entire value of the file: a golden generated after the
change pins the change, not the behaviour, and would let any of it through.

Regenerating is a deliberate act, not a fix for a failing test. If
`tests/test_grid_golden.py` fails, the question is which of the two is right --
the refactor or the golden -- and the answer is usually that the refactor
introduced a tie-break change nobody meant. `--generate` here would hide that.

What is recorded, and the choice behind each:

* `rows` / `to_dict`: the saved-encounter format. Byte-identical or a saved
  fight written before the refactor will not re-save the same.
* `distance`: every reach, range and "is it adjacent" question reads this. The
  pair is stored beside the value rather than regenerated by the reader: a golden
  whose sample the reader has to reproduce is a golden that silently starts
  comparing the wrong cells if the sampler ever drifts.
* `reachable`: `_dijkstra`'s public answer, so the loop the refactor rewrites.
* `path` **cost and step count, not the squares**: two routes of equal cost are
  the same answer for anything a player can observe, and pinning the exact route
  would fail this file on a tie-break change that changed nothing.
* `cover`: corner-to-corner wall tracing, so it catches a `_corners` derived
  from the wrong origin.
* `area`: centre-of-cell tests in plane coordinates, so it catches a `_centre`
  that is a cell corner rather than its middle.
* `visible_from`: the fog of war, where a change is a spoiler leak.

The map for the formations case is named rather than derived, because
`formations._nearest_free` needs a map with walls in it: a floor-only map
answers the same thing for every input.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import random
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from tactics import formations as _formations   # noqa: E402
from tactics import maps as _maps                # noqa: E402
from tactics.grid import Grid, area              # noqa: E402

OUT = ROOT / "tests" / "fixtures" / "grid_golden.json"
SEED = 20261003

# A map with walls, water and cover in it. `formations._nearest_free` only
# demonstrates anything where some squares are taken or impassable, and on a
# floor-only map every case returns the same cell.
FORMATIONS_MAP = "detention-bog"


def pairs(width: int, height: int, count: int = 24, seed: int = SEED):
    """The same seeded sample `test_grid_golden.py` draws, so they agree.

    Duplicated rather than imported: a generator that imported its own assertion
    file could not disagree with it, and a golden that silently follows a change
    to the sampling is a golden that quietly stops covering anything.
    """
    rng = random.Random(seed)
    out = [((0, 0), (width - 1, height - 1)),
           ((0, 0), (min(4, width - 1), min(4, height - 1))),
           ((min(1, width - 1), min(1, height - 1)),
            (max(0, width - 6), max(0, height - 6)))]
    while len(out) < count:
        a = (rng.randrange(width), rng.randrange(height))
        b = (rng.randrange(width), rng.randrange(height))
        if a != b:
            out.append((a, b))
    return out


def _plain(value):
    """JSON-safe form of what `area` returns.

    `area` answers with tuples (`{"squares": [(0, 0), ...], "origin": (2.5, 1.5)}`)
    and json.dump writes a tuple as a list, so the *fixture* is lists while a
    fresh call is tuples. Comparing them directly fails on the difference, which
    is a shape mismatch and not a behaviour change, so both sides are normalised
    through here.
    """
    if isinstance(value, dict):
        return {k: _plain(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_plain(v) for v in value]
    return value


def _reachable(grid: Grid, start, budget: int) -> list:
    got = grid.reachable(start, budget)
    return sorted([[list(k), v] for k, v in got.items()])


def generate() -> dict:
    names = sorted(_maps.available())
    if not names:
        raise SystemExit("no maps on disk; the golden would be empty")
    out = {"_about": (
        "Generated by tests/grid_golden.py --generate on origin/main BEFORE the "
        "#146 grid-seam refactor. Do not regenerate to make a failing test pass: "
        "the question a failure asks is whether the refactor or this file is "
        "right, and it is almost never this file."),
        "seed": SEED, "maps": {}}
    for name in names:
        grid = Grid.from_dict(_maps.load(name)["grid"])
        rec = {
            "rows": grid.rows,
            "to_dict": grid.to_dict(),
            "distance": [[[list(a), list(b)], grid.distance(a, b)]
                         for a, b in pairs(grid.width, grid.height, 16)],
            "reachable": [],
            "path": [],
            "cover": [],
            "area": [],
            "visible_from": [],
        }
        for start in [(0, 0), (grid.width // 2, grid.height // 2),
                      (grid.width - 1, grid.height - 1)]:
            for budget in (5, 15, 30):
                rec["reachable"].append([list(start), budget,
                                         _reachable(grid, start, budget)])
        for a, b in pairs(grid.width, grid.height, 16):
            got = grid.path(a, b, budget=40)
            rec["path"].append([list(a), list(b),
                                None if got is None
                                else {"cost": got[1], "steps": len(got[0])}])
            rec["cover"].append([[list(a), list(b)], _plain(grid.cover(a, b))])
        # Every area shape, from a fixed square, at two sizes, aimed at a fixed
        # square. `area` refuses a cone or line aimed at the caster, so the aim
        # is deliberately elsewhere and the from_self=False variants use a
        # target that is in bounds.
        aim = (min(2, grid.width - 1), min(2, grid.height - 1))
        mid = (grid.width // 2, grid.height // 2)
        for shape in ("sphere", "cylinder", "cone", "line"):
            for size in (15, 30):
                rec["area"].append([shape, size, list(mid), list(aim), True,
                                    _plain(area(grid, shape, size, mid, aim))])
        for shape in ("sphere", "cube"):
            for size in (15, 30):
                rec["area"].append([shape, size, list(mid), list(aim), False,
                                    _plain(area(grid, shape, size, mid, aim,
                                                from_self=False))])
        for origin in [(0, 0), mid, (grid.width - 1, grid.height - 1)]:
            rec["visible_from"].append(
                [list(origin), sorted([list(p) for p in grid.visible_from(origin)])])
        out["maps"][name] = rec

    board = Grid.from_dict(_maps.load(FORMATIONS_MAP)["grid"])
    cases = []
    for start in [(0, 0), (5, 5), (board.width // 2, board.height // 2),
                  (board.width - 1, board.height - 1)]:
        for taken in ([], [[1, 1]], [[0, 0]], [[0, 0], [1, 0], [0, 1], [1, 1]],
                      [[x, 0] for x in range(min(8, board.width))]):
            clipped = [[x, y] for x, y in taken if board.in_bounds((x, y))]
            got = _formations._nearest_free(board, {tuple(p) for p in clipped}, *start)
            cases.append({"want": list(start), "taken": clipped,
                          "got": list(got) if got else None})
    out["formations"] = {"map": FORMATIONS_MAP, "cases": cases}
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--generate", action="store_true",
                    help="write the fixture (run this on main, before the refactor)")
    args = ap.parse_args(argv)
    data = generate()
    if not args.generate:
        print("nothing written; pass --generate")
        return 2
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(data, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(data['maps'])} maps, "
          f"{len(data['formations']['cases'])} formation cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
