"""The square grid's behaviour, pinned before it is refactored (#146).

SPEC-grid-and-map §4.2 P1: extracting neighbour enumeration and geometry hooks so
hex can be added later is **a pure refactor for square**, and the spec's own gate
for that claim is this file:

    "Tests: new `tests/test_grid_golden.py` computes `rows`, `to_dict`,
     `reachable`, `path`, `cover` and `area` for every shipped map (and a seeded
     random pair sample) and compares against a checked-in JSON generated on
     `main` before the change."

So the fixture in `tests/fixtures/grid_golden.json` was generated by
`grid_golden.py --generate` running against `origin/main` **before** a line of
grid.py changed, and this file compares the current engine against it. That
ordering is the whole value: a golden generated after the refactor pins the
refactor, not the behaviour.

What is pinned, and why each is here:

* `rows` and `to_dict` -- the engine's storage. A saved encounter must come back
  byte-identical, so a hex key leaking into a square grid's dict is caught.
* `reachable` and `path` -- movement. These go through `_dijkstra`, which is the
  function the refactor rewrites to call a neighbour hook.
* `cover` and `area` -- the geometry consumers. `cover` traces lines between the
  four corners of unit squares, so it is what catches a `_corners` that is
  derived from the wrong thing; `area` uses centre-of-cell tests, so it catches
  a `centre` that is off by half a square.
* `distance` -- the rule every range and reach reads.
* `visible_from` -- the fog of war's answer, and a second consumer of `_corners`.

The random pair sample exists because a fixed handful of positions would not
exercise the boundaries: cells on the edge, wall seams where `_walled`'s
nudge-both-sides rule fires, and pairs far enough apart that Dijkstra's parity
bookkeeping is what decides the cost. Seeded, so a failure is reproducible and
the fixture does not churn.
"""
from __future__ import annotations

import dataclasses
import json
import pathlib
import re
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from tactics import formations as _formations   # noqa: E402
from tactics import maps as _maps                # noqa: E402
from tactics.grid import MoveOptions, Grid      # noqa: E402

GOLDEN = pathlib.Path(__file__).parent / "fixtures" / "grid_golden.json"
SEED = 20261003          # fixed, so a failure is reproducible and the file is stable


def _plain(value):
    """JSON-safe form, so a fixture read back as lists compares equal to a fresh
    call that answers in tuples.

    `area` returns `{"squares": [(0, 0), ...], "origin": (2.5, 1.5)}` and json.dump
    writes a tuple as a list, so the fixture holds lists and the live call holds
    tuples. Compared raw they differ on every entry, which is a shape mismatch and
    not a behaviour change. The generator applies the same normalisation on the
    way out, so this is a no-op when they agree and a real diff when they do not.
    """
    if isinstance(value, dict):
        return {k: _plain(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_plain(v) for v in value]
    return value


def _golden() -> dict:
    if not GOLDEN.is_file():
        pytest.fail(
            f"{GOLDEN} is missing. It is generated from origin/main BEFORE the "
            "refactor: python3 tests/grid_golden.py --generate. A golden "
            "generated afterwards pins the refactor instead of the behaviour.")
    return json.loads(GOLDEN.read_text(encoding="utf-8"))


def _pairs(width: int, height: int, count: int = 24, seed: int = SEED):
    """Seeded random square pairs, including the edges.

    A pseudo-random sample over `rng.randrange` lands on the border often enough
    to matter at this count, and the edges are exactly where `_walled`'s
    "leaving the map counts as blocked" rule and the out-of-bounds neighbour
    lookups differ from the interior. Three fixed pairs are added for the
    positions a random draw would be unlikely to produce twice: the origin, the
    far corner, and a deliberately distant pair that forces Dijkstra to settle a
    parity rather than take a straight line.
    """
    import random
    rng = random.Random(seed)
    out = [((0, 0), (width - 1, height - 1)),
           ((0, 0), (min(4, width - 1), min(4, height - 1))),
           ((min(1, width - 1), min(1, height - 1)),
            (max(0, width - 6), max(0, height - 6)))]
    while len(out) < count:
        a = (rng.randrange(width), rng.randrange(height))
        b = (rng.randrange(width), rng.randrange(height))
        if a != b:
            out.append((a, b))
    return out


def _grid_for(name: str) -> Grid:
    return Grid.from_dict(_maps.load(name)["grid"])


# ── every shipped map ─────────────────────────────────────────────────────────

SHIPPED = sorted(_maps.available())


def test_the_fixture_covers_the_shipped_maps():
    """Named, not derived from `available()`: if a map were renamed the golden
    would silently check one map fewer and every other test would still pass. The
    count is asserted too, so a golden generated from a partial tree is caught."""
    golden = _golden()
    assert golden["maps"], "the golden has no maps in it"
    missing = sorted(set(SHIPPED) - set(golden["maps"]))
    assert not missing, f"maps on disk but not in the golden: {missing}"
    stale = sorted(set(golden["maps"]) - set(SHIPPED))
    assert not stale, f"maps in the golden but not on disk: {stale}"


def test_every_shipped_map_still_compiles_to_the_same_grid():
    """`rows` and `to_dict`, byte for byte. This is the engine's saved state:
    an encounter written before the refactor has to load and re-save identically,
    which is what makes "hex is opt-in per map" true rather than aspirational."""
    golden = _golden()["maps"]
    for name in SHIPPED:
        grid = _grid_for(name)
        want = golden[name]
        assert grid.rows == want["rows"], name
        assert grid.to_dict() == want["to_dict"], name


def test_every_shipped_map_answers_distance_and_reach_the_same_way():
    golden = _golden()["maps"]
    for name in SHIPPED:
        grid = _grid_for(name)
        want = golden[name]["distance"]
        for pair, value in want:
            a, b = tuple(pair[0]), tuple(pair[1])
            assert grid.distance(a, b) == value, f"{name} {a}->{b}"
            assert grid.distance(b, a) == value, f"{name} is not symmetric at {a}->{b}"


def test_every_shipped_map_reaches_the_same_squares_for_the_same_budget():
    """`reachable` is `_dijkstra`'s public face, and `_dijkstra` is the loop the
    refactor rewrites. Compared as a sorted list of `[square, feet]` so the
    assertion is about the answer rather than dict ordering."""
    golden = _golden()["maps"]
    for name in SHIPPED:
        grid = _grid_for(name)
        want = golden[name]["reachable"]
        for start, budget, rows in want:
            got = grid.reachable(tuple(start), budget)
            assert sorted([[list(k), v] for k, v in got.items()]) == rows, (
                f"{name} reachable from {start} within {budget}")


def test_every_shipped_map_finds_the_same_path_at_the_same_cost():
    golden = _golden()["maps"]
    for name in SHIPPED:
        grid = _grid_for(name)
        for start, goal, answer in golden[name]["path"]:
            got = grid.path(tuple(start), tuple(goal), budget=40)
            if answer is None:
                assert got is None, f"{name} {start}->{goal} used to be unreachable"
                continue
            assert got is not None, f"{name} {start}->{goal} used to be reachable"
            squares, cost = got
            # The cost is the contract. The squares themselves are allowed to
            # differ where two routes tie, because a tie-break change is not a
            # behaviour change and pinning the exact route would fail this file
            # for a refactor that changed nothing a player can observe. A *cheaper*
            # route than the golden is a real bug: Dijkstra was already returning
            # the minimum, so that would mean the search stopped looking.
            assert cost == answer["cost"], f"{name} {start}->{goal}"
            assert squares[0] == tuple(start) and squares[-1] == tuple(goal)
            assert len(squares) == answer["steps"], (
                f"{name} {start}->{goal}: the route changed length at the same "
                f"cost, which means a tie-break moved")


def test_every_shipped_map_draws_the_same_sight_lines_and_cover():
    """`cover` traces lines between the four corners of unit squares and
    `visible_from` uses the same corners, so this is what catches a `_corners`
    derived from the wrong origin -- an off-by-one there shifts every wall and
    changes cover without changing a single row."""
    golden = _golden()["maps"]
    for name in SHIPPED:
        grid = _grid_for(name)
        for pair, want in golden[name]["cover"]:
            a, b = (tuple(pair[0]), tuple(pair[1]))
            assert _plain(grid.cover(a, b)) == want, f"{name} cover {a}->{b}"


def test_every_shipped_map_places_the_same_areas():
    """`area` uses centre-of-cell tests in plane coordinates. A `centre` hook
    that is the cell's corner instead of its middle shifts every area by half a
    square, which is invisible on a sparse map and wrong on a dense one."""
    golden = _golden()["maps"]
    for name in SHIPPED:
        grid = _grid_for(name)
        for shape, size, caster, target, from_self, want in golden[name]["area"]:
            got = grid_area(grid, shape, size, tuple(caster), tuple(target),
                            from_self)
            assert _plain(got) == want, (
                f"{name} {shape} {size} from {caster} to {target} "
                f"(from_self={from_self})")


def grid_area(grid, shape, size, caster, target, from_self=True):
    """`area` is a module function taking the grid, not a Grid method (grid.py).

    `from_self` is stored in the fixture rather than assumed, because a sphere
    centred on the caster and a sphere centred on the aim are different answers
    and reading the flag off the wrong side of that distinction compares an origin
    of (2.5, 1.5) against (2.5, 2.5) -- a mismatch that looks like a behaviour
    change and is a bookkeeping one.
    """
    from tactics.grid import area
    return area(grid, shape, size, caster, target, from_self=from_self)


def test_every_shipped_map_sees_the_same_squares():
    """The fog-of-war answer. `visible_from` is cached per grid and is what a
    player's snapshot hides unseen creatures behind, so a change here is a
    spoiler leak rather than a rendering difference."""
    golden = _golden()["maps"]
    for name in SHIPPED:
        grid = _grid_for(name)
        for origin, want in golden[name]["visible_from"]:
            assert sorted([list(p) for p in grid.visible_from(tuple(origin))]) == want


# ── formations use the neighbour API, and the seam is where it should be ─────

def test_formation_placement_finds_the_same_free_square():
    """`formations._nearest_free` (formations.py:577) enumerates its own 8
    neighbours with a nested `for dx in (-1, 0, 1)` loop. That is the square
    assumption the refactor replaces with the neighbour hook, so this pins the
    answer *before and after*: the refactor must not change which square a
    formation occupies, only how the candidate squares are enumerated.

    Generated from `main`, so on `main` this asserts the current behaviour and
    after the refactor it asserts the same thing. That is the whole criterion
    "formations use neighbor API" measured as behaviour rather than as a diff.
    """
    golden = _golden()["formations"]
    grid = _grid_for(golden["map"])
    for case in golden["cases"]:
        taken = {tuple(p) for p in case["taken"]}
        got = _formations._nearest_free(grid, taken, *case["want"])
        assert got == (tuple(case["got"]) if case["got"] else None), case


def test_the_generator_and_this_file_sample_the_same_pairs():
    """Only `reachable` still relies on this: it stores a start and a budget but
    not the squares, because its own answer is every square found. The pairs for
    `distance`, `cover` and `path` are stored in the fixture beside their values,
    so a drifted sampler cannot silently misalign them.

    `reachable` is the case that still relies on the agreement, because it stores
    a start and a budget rather than the squares it found. Nothing about a
    drifted copy would fail there: the assertions would simply compare different
    budgets and pass or fail for the wrong reason.

    So the two bodies are compared. The generator cannot import this file to do
    it -- a generator that shared its sampler's source with the assertions could
    not disagree with them, and a golden that quietly follows a change to the
    sampling is a golden that has stopped covering anything.
    """
    import re
    generator = (ROOT / "tests" / "grid_golden.py").read_text(encoding="utf-8")
    here = pathlib.Path(__file__).read_text(encoding="utf-8")

    def body(src: str, name: str):
        m = re.search(r"def " + name + r"\(.*?\n(.*?)(?=\ndef |\nclass |\n# ---)", src, re.S)
        assert m, f"{name} not found"
        return m.group(0)

    def logic(src: str) -> list:
        # Docstrings and comments carry the argument for why the two copies exist
        # and are allowed to differ; the executable lines are the contract. An
        # `import` is dropped from both sides because one copy imports `random`
        # locally and the other at module scope, which is not a behaviour
        # difference.
        src = re.sub(r'""".*?"""', "", src, flags=re.S)
        out = []
        for line in src.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or line.startswith(("import ", "from ")):
                continue
            out.append(line)
        return out

    a = logic(body(generator, "pairs"))
    b = logic(body(here, "_pairs"))
    # The two differ only in the function's own name.
    a = [line.replace("def pairs(", "def _pairs(") for line in a]
    b = [line.replace("def _pairs(", "def _pairs(") for line in b]
    assert a == b, ("the sampler in grid_golden.py and the one here have "
                    f"diverged:\n  generator: {a}\n  this file:  {b}")


def test_no_caller_outside_grid_py_touches_the_private_geometry():
    """The inventory criterion, as a check rather than a list in a comment.

    SPEC 4.2's claim is that the engine's geometry lives behind four hooks and
    everything else speaks to the grid through `distance`, `cover`, `visible_from`
    and the rest. That claim is only worth anything if it stays true, and the way
    it stops being true is a caller reaching into `_corners` or `_walled` for a
    one-off. This fails the day that happens, which is before hex does.

    The names are listed rather than derived by pattern because "private" has no
    mechanical meaning in Python; the list is the contract, and adding to it is
    a decision someone makes rather than an accident.
    """
    private = ("_corners", "_dijkstra", "_step_cost", "_segment_hits",
               "_cells_between", "_walled", "_cover", "_cell_polygon")
    offenders = []
    for path in (ROOT / "scripts" / "tactics").glob("*.py"):
        if path.name == "grid.py":
            continue
        for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.split("#", 1)[0]
            for name in private:
                if f".{name}(" in stripped or f"board.{name}(" in stripped:
                    offenders.append(f"{path.relative_to(ROOT)}:{n} {name}")
    assert not offenders, (
        "callers outside grid.py reach into the private geometry, which is "
        f"exactly what the seams exist to prevent: {offenders}")


def test_the_only_square_rule_remaining_is_distance_itself():
    """`distance` is a method every caller already goes through, so hex needs no
    caller change: a hex grid returns 5 ft per edge and each `distance(...) <= 5`
    adjacency test, `distance(...) > reach` range test and `min(...)` nearest-
    enemy search keeps working. This asserts those callers are still calling it,
    by counting the call sites in the modules that lean on it.

    Not a coverage claim: it is a tripwire for the shape of the refactor. If a
    future change replaced a `distance` call with hand-rolled `abs(dx)` arithmetic
    -- the one way to make this grid quietly square-only -- the count drops and
    this says so.
    """
    callers = {}
    for name in ("actions", "ai", "effects", "engine", "fightq", "policy",
                 "spells", "statecard", "formations"):
        path = ROOT / "scripts" / "tactics" / f"{name}.py"
        text = path.read_text(encoding="utf-8")
        callers[name] = len(re.findall(r"\.distance\(", text))
    # engine dropped 9 -> 3 with #257, and the drop is the point rather than a
    # loss: six of those sites were asking "how far is this creature" and were
    # answered from its anchor square. They now go through `min_distance` (the
    # nearest square of the body) or `adjacent` (squares that touch), both of
    # which are `distance` asked about a footprint and both of which reduce to
    # this exact call for two 1x1 creatures. The three that remain are
    # `approach`, which is placing one creature beside another and asks about a
    # single destination square by design.
    # Exact, not a floor. A floor of 20 survived a mutant that replaced one call
    # with hand-rolled `max(abs(dx), abs(dy)) * 5`, which is exactly the change
    # this is meant to catch -- so the threshold was loose enough to miss the one
    # thing it exists for. An exact count fails when a call site is added too,
    # which is the intended friction: moving a distance question is a decision
    # about geometry and should say so in a test.
    assert callers == {"actions": 1, "ai": 5, "effects": 3, "engine": 3,
                       "fightq": 3, "policy": 1, "spells": 1, "statecard": 2,
                       "formations": 0}, (
        f"the Grid.distance call sites moved: {callers}. Either a caller started "
        "computing dx/dy by hand, which is the square-only path hex cannot take, "
        "or a new caller arrived and this inventory needs updating deliberately.")


def test_the_neighbour_enumeration_has_a_single_source():
    """The point of the seam, asserted in the source rather than in behaviour.

    A square grid has exactly one place that knows what a neighbour is. If a
    second `for dx in (-1, 0, 1)` appears outside `Grid.neighbors`, hex has
    found a way to be wrong that no behaviour test above would catch -- because
    they all test square behaviour, which is exactly what hex is meant to
    preserve while changing the enumeration underneath it.

    **This test fails on `origin/main`**, which is correct: on main the
    enumeration lives in `Grid._dijkstra` and again in `formations._nearest_free`,
    and the refactor is what collapses them into one hook. It is written before
    the refactor so that "one source" is a checked property of the change rather
    than a claim about it.
    """
    offenders = []
    for path in (ROOT / "scripts" / "tactics").glob("*.py"):
        text = path.read_text(encoding="utf-8")
        if path.name == "grid.py":
            continue
        for n, line in enumerate(text.splitlines(), 1):
            if "for dx in (-1, 0, 1)" in line or "for dy in (-1, 0, 1)" in line:
                offenders.append(f"{path.relative_to(ROOT)}:{n}")
    assert not offenders, (
        f"square neighbour enumeration outside Grid.neighbors: {offenders}")


def test_move_options_are_still_the_default_and_immutable():
    """`MoveOptions` is a `@dataclass` (not frozen) holding `frozenset` defaults,
    and every caller builds it by keyword. The frozensets are the part that
    matters: `Grid.reachable` and `_dijkstra` key their results on them, so a
    mutable default would make a cache entry depend on who asked last. Asserted
    on the values and on the types rather than on `frozen=True`, which
    `MoveOptions` does not use and this refactor must not add -- nothing needs
    it and it would break any caller that builds options incrementally."""
    opts = MoveOptions()
    assert opts.blocked == frozenset() and opts.occupied == frozenset()
    assert opts.crawling is False and opts.swim is False
    assert isinstance(opts.blocked, frozenset) and isinstance(opts.occupied, frozenset)
    # The dataclass fields are exactly these four: a refactor that added one
    # with a mutable default would break the caches above silently.
    assert [f.name for f in dataclasses.fields(opts)] == [
        "blocked", "occupied", "crawling", "swim"]
