#!/usr/bin/env python3
"""install_srd_art.py: fetch a portrait for every SRD creature, into a gitignored pool.

Run:
    python3 scripts/install_srd_art.py --check
    python3 scripts/install_srd_art.py --out display/srd-art --size 256
    python3 scripts/install_srd_art.py --out display/srd-art --only aboleth,acolyte

WHY THIS IS A SEPARATE SCRIPT AND A SEPARATE DIRECTORY
======================================================

`install_tokens.py` installs the hearden pack. This installs a different set of
pictures, from a different author, under a different licence position, and the
two must never be confused for one another at a glance. So: a different
directory, a different manifest constant, and this file.

THE ART IS NOT LICENSED. DO NOT COMMIT IT.
===========================================

The PNGs come from the public bucket behind dnd5eapi.co. Two things have to be
said plainly, because the first is the one that is easy to get wrong:

  * They are not SRD artwork and no SRD term reaches them. SRD 5.1's OGL
    defines Product Identity to include "artwork ... and other visual ...
    representations" and lists those as NOT Open Content. The rules licence
    covers rules text. It never licensed art, in either direction, so
    "the SRD is CC-BY" is not an argument for anything here.

  * They carry no licence of their own. dnd5eapi.co publishes no terms page.
    `5e-bits/5e-database` and `5e-srd-api` are MIT, which licenses the SOFTWARE
    and says nothing about a bucket's contents -- and the images are in neither
    repository. Their own PNG text chunks name stable-diffusion-1.5, so they
    are AI-generated by volunteers. Stability AI waives claims in its own
    output, which clears Stability and not the human who prompted it.

So the art lands in `display/srd-art/`, which `.gitignore` excludes, and the
manifest that names the set IS committed. That is exactly the arrangement
`display/tokens/` already uses, and the reason for it is one line in
`display/maps/README.md`: free to download is not free of the author's claim.

Personal, offline use in your own vault is a defensible position. Adding these
to a repository you publish is not one, and this script will not help you do it.

WHY A POOL AND NOT A FIELD
==========================

`build_srd.py` already carries each creature's art ADDRESS, and the notes carry
it, and that is enough for a note to render a portrait in Obsidian. What it
cannot do is put the file in Atlas, because Atlas needs a real local path.

A pool is how this codebase already solves that, and it is the whole of the
match: the art is named by the same slug the statblock is, so
`statblock_art.py` finds `aboleth.png` for "Aboleth" by exact match with no
inference, no similarity search, and no new code path. A creature matched this
way is matched on its own name; a creature with no file here stays uncovered and
is still printed by name, which is the report's job.

That last point is why this is a pool and not a filling-in step. Nothing here
substitutes: if the download failed, or the slug is absent, that creature has no
portrait and says so. It is the only honest failure mode, because a creature
standing at the table wearing the wrong face is a bug no check will ever catch.

SIZE, AND WHY NOT SQUARE
========================

The upstream pictures are mixed -- 768x512 and 1024x1024 -- so most are
landscape, and the token convention here is a 256px square. Resizing a 3:2
picture into a square distorts it, and a stretched face is the same failure as
a wrong one, so this scales the LONGEST edge to `--size` and leaves the aspect
alone. The result is smaller than a square would be, and correct.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
import time
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_DATA = ROOT / "systems" / "dnd5e" / "data" / "dnd5e_srd.json"
DEFAULT_OUT = ROOT / "display" / "srd-art"

# The same bucket the API proxies, read directly: one fewer hop, and the host
# is the thing actually serving the bytes.
SOURCE = "https://dnd-5e-api-images.s3.us-west-1.amazonaws.com/monsters/{slug}.png"
IMAGE = SOURCE
CREDIT = "5e-bits contributors (AI-generated, Stable Diffusion 1.5)"

# The bucket belongs to a volunteer paying real money for it. Identify
# ourselves, and stay slow. 334 files at this delay is about two minutes, which
# is well inside anything a volunteer would object to.
UA = "dnd-gm-portrait-fetch/1.0 (personal offline VTT art; +https://github.com/5e-bits/5e-srd-api)"
DELAY = 0.35
RETRIES = 3
TIMEOUT = 30
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"


def _as_png(body: bytes, size: int) -> bytes | None:
    """Re-encode to a sized PNG, or None if these bytes are not an image.

    The bytes, not the filename and not the Content-Type, decide. Both of those
    lie upstream: `brown-bear.png` is served as `image/png` and is a JPEG with
    Exif, so a status check or a magic-byte check alone either writes a JPEG to a
    `.png` name or -- worse -- silently drops the one creature that came back
    mislabelled. Opening it is the only test that answers the question actually
    being asked, which is whether a usable picture is here.
    """
    import io

    try:
        from PIL import Image
    except ImportError:
        # Without Pillow we can neither re-encode nor be sure. Returning the body
        # unchanged would risk a JPEG under a .png name, so this refuses instead
        # and says why.
        print("  Pillow is not installed: cannot verify or resize. "
              "pip install Pillow and re-run.", file=sys.stderr)
        return None
    try:
        with Image.open(io.BytesIO(body)) as im:
            im.load()
            if im.mode not in ("RGB", "RGBA"):
                im = im.convert("RGBA")
            if max(im.size) > size:
                scale = size / max(im.size)
                im = im.resize((max(1, round(im.width * scale)),
                                max(1, round(im.height * scale))),
                               Image.LANCZOS)
            buf = io.BytesIO()
            im.save(buf, format="PNG", optimize=True)
            return buf.getvalue()
    except Exception as exc:  # noqa: BLE001 - a bad file is skipped, not fatal
        print(f"  not a readable image ({type(exc).__name__}: {exc})", file=sys.stderr)
        return None


def slugs_from(path: pathlib.Path) -> list[str]:
    """Every monster `index` in the project's own generated dataset.

    Read from the dataset rather than from an API index so the set is exactly
    the set this project knows about. These values are identical to the API's
    own, so nothing has to be translated, and a creature the project does not
    have is not fetched for a statblock that does not exist.
    """
    data = json.loads(path.read_text(encoding="utf-8"))
    monsters = data["monsters"] if isinstance(data, dict) else data
    return sorted({m["index"] for m in monsters if m.get("index")})


def _shrink(body: bytes, size: int) -> bytes | None:
    """Kept for symmetry with `_as_png`; all resizing now happens there."""
    return _as_png(body, size)


def fetch(slug: str, out: pathlib.Path, size: int) -> tuple[str, int]:
    """One creature. Returns (slug, bytes) or (slug, 0) with the reason on stderr."""
    dest = out / f"{slug}.png"
    url = IMAGE.format(slug=slug)
    last = ""
    for attempt in range(1, RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=TIMEOUT) as response:
                body = response.read()
                ctype = response.headers.get("Content-Type", "")
            # The bucket answers 403 with a 263-byte HTML page for a slug it does
            # not have, so a status check alone would write an error page to a
            # filename that means "creature". The bytes decide instead.
            if not body.startswith(PNG_MAGIC):
                last = f"not a PNG ({ctype}, {len(body)}B) - trying to decode it"
            png = _as_png(body, size)
            if png is None:
                last = last or f"unreadable ({ctype}, {len(body)}B)"
            else:
                dest.write_bytes(png)
                return slug, len(png)
        except urllib.error.HTTPError as exc:
            last = f"HTTP {exc.code}"
            if exc.code in (403, 404):
                break          # a slug that is not there will not become one
        except Exception as exc:  # noqa: BLE001 - the network is allowed to be flaky
            last = f"{type(exc).__name__}: {exc}"
        if attempt < RETRIES:
            time.sleep(1.5 * attempt)
    print(f"  {slug}: FAILED ({last})", file=sys.stderr)
    return slug, 0


def check(out: pathlib.Path, data: pathlib.Path) -> int:
    """Report which creatures have art here and which do not, writing nothing."""
    wanted = slugs_from(data)
    have = {p.stem for p in out.glob("*.png")} if out.is_dir() else set()
    missing = [s for s in wanted if s not in have]
    extra = sorted(have - set(wanted))
    print(f"{out}: {len(have)} portrait(s)")
    print(f"  creatures in the dataset: {len(wanted)}")
    print(f"  with art:                 {len(wanted) - len(missing)}")
    print(f"  without art:              {len(missing)}")
    if extra:
        print(f"  files here for no creature in the dataset: {len(extra)}")
        for name in extra[:20]:
            print(f"    {name}")
    if missing:
        print("  no portrait, by name -- this list is the deliverable:")
        for name in missing:
            print(f"    {name}")
    return 1 if missing else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT,
                        help=f"where the art goes (default {DEFAULT_OUT.name}/). "
                             "Must be gitignored; it is not committable art.")
    parser.add_argument("--data", type=pathlib.Path, default=DEFAULT_DATA,
                        help="the generated SRD dataset to read creature names from")
    parser.add_argument("--size", type=int, default=256,
                        help="longest edge in pixels, aspect preserved (default 256)")
    parser.add_argument("--only", default="",
                        help="comma-separated creature slugs, skips the full run")
    parser.add_argument("--delay", type=float, default=DELAY,
                        help="seconds between requests; raise it to be politer")
    parser.add_argument("--check", action="store_true",
                        help="report coverage and write nothing at all")
    args = parser.parse_args(argv)

    if not args.data.exists():
        print(f"{args.data} is missing. It is generated and gitignored: run "
              f"python3 systems/dnd5e/build_srd.py first.", file=sys.stderr)
        return 1

    if args.check:
        return check(args.out, args.data)

    wanted = ([s.strip() for s in args.only.split(",") if s.strip()]
              or slugs_from(args.data))
    print(f"install_srd_art: {len(wanted)} creature(s) -> {args.out}")
    print(f"  source  {IMAGE.format(slug='<slug>')}")
    print(f"  credit  {CREDIT}")
    print(f"  LICENCE none published. This art is NOT committable and {args.out} "
          f"is gitignored for that reason.")

    args.out.mkdir(parents=True, exist_ok=True)
    fetched = failed = skipped = 0
    total = 0
    for i, slug in enumerate(wanted, 1):
        dest = args.out / f"{slug}.png"
        if dest.exists() and dest.stat().st_size > 0:
            skipped += 1        # resumable: never re-pull what is already here
            continue
        _, size = fetch(slug, args.out, args.size)
        if size:
            fetched += 1
            total += size
            print(f"  [{i}/{len(wanted)}] {slug}: {size:,}B")
        else:
            failed += 1
        time.sleep(args.delay)

    print(f"\ndone: {fetched} fetched, {skipped} already present, "
          f"{failed} failed, {total / 1e6:.1f} MB")
    if failed:
        print("A creature with no file is UNCOVERED, not approximated. "
              "statblock_art.py will print its name.")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
